---
- name: 'Check if vmwaretools is installed'
  ansible.windows.win_stat:
    path: 'C:\Program Files\VMware\VMware Tools\vmtoolsd.exe'
  register: _vmwaretools_is_installed

- name: 'Check current iVMware tools version'
  ansible.windows.win_command: '"C:\Program Files\VMware\VMware Tools\vmtoolsd.exe" --version'
  failed_when: false
  changed_when: false
  register: _vmwaretools_version_check

- name: 'Download and unarchive Windows Exporter'
  when:
    - not _vmwaretools_is_installed.stat.exists or
      ( _vmwaretools_version_check.stderr_lines | length > 0 and
      vmwaretools_version not in _vmwaretools_version_check.stderr_lines[0].split(" ")[2] ) or
      ( _vmwaretools_version_check.stdout_lines | length > 0 and
      vmwaretools_version not in _vmwaretools_version_check.stdout_lines[0].split(" ")[2] )
  block:
    # - name: 'Download Windows Exporter into temporary location'
    #   ansible.windows.win_get_url:
    #     url: '{{ windows_exporter_download_url }}/{{ windows_exporter_package_name }}'
    #     dest: '{{ ansible_env.TEMP }}\{{ windows_exporter_package_name }}'
    #   check_mode: false

    # - name: 'Install Windows Exporter'
    #   ansible.windows.win_package:
    #     path: '{{ ansible_env.TEMP }}\{{ windows_exporter_package_name }}'
    #     state: present
    #   when: not ansible_check_mode

    - name: Create Directory if not exist
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: Download exe to winbox
      ansible.windows.win_get_url:
        url: https://packages.vmware.com/tools/esx/latest/windows/x64/VMware-tools-11.1.1-16303738-x86_64.exe
        dest: C:\temp\VMware-tools-11.1.1-16303738-x86_64.exe

    - name: Install Vmware tools Silent
      ansible.windows.win_command: C:\temp\VMware-tools-11.1.1-16303738-x86_64.exe /S /v "/qn REBOOT=R ADDLOCAL=ALL REMOVE=Hgfs"
